version: "3.7"

services:
  prometheus:
    image: siddharthpatel1/prometheus:v1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    tty: true
    networks:
      - pg_network

  node_exporter:
    image: siddharthpatel1/nodeexporter:v1
    container_name: node_exporter
    restart: unless-stopped
    mem_limit: "1g"
    mem_reservation: "512m"
    ports:
      - "9100:9100"
    tty: true
    networks:
      - pg_network

  grafana:
    image: siddharthpatel1/grafana:v1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    networks:
      - pg_network

  alertmanager:
    image: siddharthpatel1/alertmanager:v1
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    tty: true
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
