version: "3.7"

services:
  django:
    image: siddharthpatel1/django:v1
    container_name: django
    restart: unless-stopped
    ports:
      - "8000:8000"
    tty: true
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

