version: "3.7"

services:
  apacheserver:
    image: siddharthpatel1/apache:v1
    container_name: apacheserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    tty: true
    networks:
      - apache_network

networks:
  apache_network:
    driver: bridge

